/*
 * Copyright 2010 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2017-09-26 19:19:48 UTC)
 * on 2017-10-23 at 22:53:17 UTC 
 * Modify at your own risk.
 */

package com.cloudaware.cloudmine.appengine.model.cloudtasks.v2beta2;

/**
 * Deprecated. Use AppEngineHttpRequest.
 * <p>
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Cloud Tasks API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class AppEngineTaskTarget {

    /**
     * Deprecated. Use AppEngineHttpRequest.app_engine_routing.
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private AppEngineRouting appEngineRouting;

    /**
     * Deprecated. Use AppEngineHttpRequest.headers.
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.util.Map<String, String> headers;

    /**
     * Deprecated. Use AppEngineHttpRequest.http_method.
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private String httpMethod;

    /**
     * Deprecated. Use AppEngineHttpRequest.payload.
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private String payload;

    /**
     * Deprecated. Use AppEngineHttpRequest.relative_url.
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private String relativeUrl;

    /**
     * Deprecated. Use AppEngineHttpRequest.app_engine_routing.
     *
     * @return value or {@code null} for none
     */
    public AppEngineRouting getAppEngineRouting() {
        return appEngineRouting;
    }

    /**
     * Deprecated. Use AppEngineHttpRequest.app_engine_routing.
     *
     * @param appEngineRouting appEngineRouting or {@code null} for none
     */
    public AppEngineTaskTarget setAppEngineRouting(AppEngineRouting appEngineRouting) {
        this.appEngineRouting = appEngineRouting;
        return this;
    }

    /**
     * Deprecated. Use AppEngineHttpRequest.headers.
     *
     * @return value or {@code null} for none
     */
    public java.util.Map<String, String> getHeaders() {
        return headers;
    }

    /**
     * Deprecated. Use AppEngineHttpRequest.headers.
     *
     * @param headers headers or {@code null} for none
     */
    public AppEngineTaskTarget setHeaders(java.util.Map<String, String> headers) {
        this.headers = headers;
        return this;
    }

    /**
     * Deprecated. Use AppEngineHttpRequest.http_method.
     *
     * @return value or {@code null} for none
     */
    public String getHttpMethod() {
        return httpMethod;
    }

    /**
     * Deprecated. Use AppEngineHttpRequest.http_method.
     *
     * @param httpMethod httpMethod or {@code null} for none
     */
    public AppEngineTaskTarget setHttpMethod(String httpMethod) {
        this.httpMethod = httpMethod;
        return this;
    }

    /**
     * Deprecated. Use AppEngineHttpRequest.payload.
     *
     * @return value or {@code null} for none
     * @see #decodePayload()
     */
    public String getPayload() {
        return payload;
    }

    /**
     * Deprecated. Use AppEngineHttpRequest.payload.
     *
     * @param payload payload or {@code null} for none
     * @see #encodePayload()
     */
    public AppEngineTaskTarget setPayload(String payload) {
        this.payload = payload;
        return this;
    }

    /**
     * Deprecated. Use AppEngineHttpRequest.payload.
     *
     * @return Base64 decoded value or {@code null} for none
     * @see #getPayload()
     * @since 1.14
     */
    public byte[] decodePayload() {
        return com.google.api.client.util.Base64.decodeBase64(payload);
    }

    /**
     * Deprecated. Use AppEngineHttpRequest.payload.
     *
     * @see #setPayload()
     * <p>
     * <p>
     * The value is encoded Base64 or {@code null} for none.
     * </p>
     * @since 1.14
     */
    public AppEngineTaskTarget encodePayload(byte[] payload) {
        this.payload = com.google.api.client.util.Base64.encodeBase64URLSafeString(payload);
        return this;
    }

    /**
     * Deprecated. Use AppEngineHttpRequest.relative_url.
     *
     * @return value or {@code null} for none
     */
    public String getRelativeUrl() {
        return relativeUrl;
    }

    /**
     * Deprecated. Use AppEngineHttpRequest.relative_url.
     *
     * @param relativeUrl relativeUrl or {@code null} for none
     */
    public AppEngineTaskTarget setRelativeUrl(String relativeUrl) {
        this.relativeUrl = relativeUrl;
        return this;
    }

}
