/*
 * Copyright 2010 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2017-09-26 19:19:48 UTC)
 * on 2017-10-23 at 22:53:17 UTC 
 * Modify at your own risk.
 */

package com.cloudaware.cloudmine.appengine.model.cloudtasks.v2beta2;

/**
 * Status of the task.
 * <p>
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Cloud Tasks API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class TaskStatus {

    /**
     * Output only.
     * <p>
     * The number of attempts dispatched. This count includes tasks which have been dispatched but
     * haven't received a response.
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    @com.google.api.client.json.JsonString
    private Long attemptDispatchCount;

    /**
     * Output only.
     * <p>
     * The number of attempts which have received a response.
     * <p>
     * This field is not calculated for [pull tasks](google.cloud.tasks.v2beta2.PullTaskTarget).
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    @com.google.api.client.json.JsonString
    private Long attemptResponseCount;

    /**
     * Output only.
     * <p>
     * The status of the task's first attempt.
     * <p>
     * Only AttemptStatus.dispatch_time will be set. The other AttemptStatus information is not
     * retained by Cloud Tasks.
     * <p>
     * This field is not calculated for [pull tasks](google.cloud.tasks.v2beta2.PullTaskTarget).
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private AttemptStatus firstAttemptStatus;

    /**
     * Output only.
     * <p>
     * The status of the task's last attempt.
     * <p>
     * This field is not calculated for [pull tasks](google.cloud.tasks.v2beta2.PullTaskTarget).
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private AttemptStatus lastAttemptStatus;

    /**
     * Output only.
     * <p>
     * The number of attempts dispatched. This count includes tasks which have been dispatched but
     * haven't received a response.
     *
     * @return value or {@code null} for none
     */
    public Long getAttemptDispatchCount() {
        return attemptDispatchCount;
    }

    /**
     * Output only.
     * <p>
     * The number of attempts dispatched. This count includes tasks which have been dispatched but
     * haven't received a response.
     *
     * @param attemptDispatchCount attemptDispatchCount or {@code null} for none
     */
    public TaskStatus setAttemptDispatchCount(Long attemptDispatchCount) {
        this.attemptDispatchCount = attemptDispatchCount;
        return this;
    }

    /**
     * Output only.
     * <p>
     * The number of attempts which have received a response.
     * <p>
     * This field is not calculated for [pull tasks](google.cloud.tasks.v2beta2.PullTaskTarget).
     *
     * @return value or {@code null} for none
     */
    public Long getAttemptResponseCount() {
        return attemptResponseCount;
    }

    /**
     * Output only.
     * <p>
     * The number of attempts which have received a response.
     * <p>
     * This field is not calculated for [pull tasks](google.cloud.tasks.v2beta2.PullTaskTarget).
     *
     * @param attemptResponseCount attemptResponseCount or {@code null} for none
     */
    public TaskStatus setAttemptResponseCount(Long attemptResponseCount) {
        this.attemptResponseCount = attemptResponseCount;
        return this;
    }

    /**
     * Output only.
     * <p>
     * The status of the task's first attempt.
     * <p>
     * Only AttemptStatus.dispatch_time will be set. The other AttemptStatus information is not
     * retained by Cloud Tasks.
     * <p>
     * This field is not calculated for [pull tasks](google.cloud.tasks.v2beta2.PullTaskTarget).
     *
     * @return value or {@code null} for none
     */
    public AttemptStatus getFirstAttemptStatus() {
        return firstAttemptStatus;
    }

    /**
     * Output only.
     * <p>
     * The status of the task's first attempt.
     * <p>
     * Only AttemptStatus.dispatch_time will be set. The other AttemptStatus information is not
     * retained by Cloud Tasks.
     * <p>
     * This field is not calculated for [pull tasks](google.cloud.tasks.v2beta2.PullTaskTarget).
     *
     * @param firstAttemptStatus firstAttemptStatus or {@code null} for none
     */
    public TaskStatus setFirstAttemptStatus(AttemptStatus firstAttemptStatus) {
        this.firstAttemptStatus = firstAttemptStatus;
        return this;
    }

    /**
     * Output only.
     * <p>
     * The status of the task's last attempt.
     * <p>
     * This field is not calculated for [pull tasks](google.cloud.tasks.v2beta2.PullTaskTarget).
     *
     * @return value or {@code null} for none
     */
    public AttemptStatus getLastAttemptStatus() {
        return lastAttemptStatus;
    }

    /**
     * Output only.
     * <p>
     * The status of the task's last attempt.
     * <p>
     * This field is not calculated for [pull tasks](google.cloud.tasks.v2beta2.PullTaskTarget).
     *
     * @param lastAttemptStatus lastAttemptStatus or {@code null} for none
     */
    public TaskStatus setLastAttemptStatus(AttemptStatus lastAttemptStatus) {
        this.lastAttemptStatus = lastAttemptStatus;
        return this;
    }

}
