/*
 * Copyright 2010 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2017-09-26 19:19:48 UTC)
 * on 2017-10-23 at 22:53:17 UTC 
 * Modify at your own risk.
 */

package com.cloudaware.cloudmine.appengine.model.cloudtasks;

/**
 * The status of a task attempt.
 * <p>
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Cloud Tasks API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class AttemptStatus {

    /**
     * Output only.
     * <p>
     * The time that this attempt was dispatched.
     * <p>
     * `dispatch_time` will be truncated to the nearest microsecond.
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private String dispatchTime;

    /**
     * Output only.
     * <p>
     * The response from the target for this attempt.
     * <p>
     * If the task has not been attempted or the task is currently running then the response status is
     * google.rpc.Code.UNKNOWN.
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private Status responseStatus;

    /**
     * Output only.
     * <p>
     * The time that this attempt response was received.
     * <p>
     * `response_time` will be truncated to the nearest microsecond.
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private String responseTime;

    /**
     * Output only.
     * <p>
     * The time that this attempt was scheduled.
     * <p>
     * `schedule_time` will be truncated to the nearest microsecond.
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private String scheduleTime;

    /**
     * Output only.
     * <p>
     * The time that this attempt was dispatched.
     * <p>
     * `dispatch_time` will be truncated to the nearest microsecond.
     *
     * @return value or {@code null} for none
     */
    public String getDispatchTime() {
        return dispatchTime;
    }

    /**
     * Output only.
     * <p>
     * The time that this attempt was dispatched.
     * <p>
     * `dispatch_time` will be truncated to the nearest microsecond.
     *
     * @param dispatchTime dispatchTime or {@code null} for none
     */
    public AttemptStatus setDispatchTime(String dispatchTime) {
        this.dispatchTime = dispatchTime;
        return this;
    }

    /**
     * Output only.
     * <p>
     * The response from the target for this attempt.
     * <p>
     * If the task has not been attempted or the task is currently running then the response status is
     * google.rpc.Code.UNKNOWN.
     *
     * @return value or {@code null} for none
     */
    public Status getResponseStatus() {
        return responseStatus;
    }

    /**
     * Output only.
     * <p>
     * The response from the target for this attempt.
     * <p>
     * If the task has not been attempted or the task is currently running then the response status is
     * google.rpc.Code.UNKNOWN.
     *
     * @param responseStatus responseStatus or {@code null} for none
     */
    public AttemptStatus setResponseStatus(Status responseStatus) {
        this.responseStatus = responseStatus;
        return this;
    }

    /**
     * Output only.
     * <p>
     * The time that this attempt response was received.
     * <p>
     * `response_time` will be truncated to the nearest microsecond.
     *
     * @return value or {@code null} for none
     */
    public String getResponseTime() {
        return responseTime;
    }

    /**
     * Output only.
     * <p>
     * The time that this attempt response was received.
     * <p>
     * `response_time` will be truncated to the nearest microsecond.
     *
     * @param responseTime responseTime or {@code null} for none
     */
    public AttemptStatus setResponseTime(String responseTime) {
        this.responseTime = responseTime;
        return this;
    }

    /**
     * Output only.
     * <p>
     * The time that this attempt was scheduled.
     * <p>
     * `schedule_time` will be truncated to the nearest microsecond.
     *
     * @return value or {@code null} for none
     */
    public String getScheduleTime() {
        return scheduleTime;
    }

    /**
     * Output only.
     * <p>
     * The time that this attempt was scheduled.
     * <p>
     * `schedule_time` will be truncated to the nearest microsecond.
     *
     * @param scheduleTime scheduleTime or {@code null} for none
     */
    public AttemptStatus setScheduleTime(String scheduleTime) {
        this.scheduleTime = scheduleTime;
        return this;
    }

}
