/*
 * Copyright 2010 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2017-02-15 17:18:02 UTC)
 * on 2017-06-16 at 01:10:20 UTC
 * Modify at your own risk.
 */

package com.cloudaware.cloudmine.appengine.model.cloudtasks;

/**
 * Retry config.
 * <p>
 * These settings determine retry behavior.
 * <p>
 * If a task does not complete successfully, meaning that an acknowledgement is not received from
 * the handler before the
 * [deadline](https://cloud.google.com/appengine/docs/python/taskqueue/push/#the_task_deadline),
 * then it will be retried with exponential backoff according to the settings in RetryConfig.
 * <p>
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Cloud Tasks API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class RetryConfig {

    /**
     * The maximum number of attempts for a task.
     * <p>
     * Cloud Tasks will attempt the task `max_attempts` times (that is, if the first attempt fails,
     * then there will be `max_attempts - 1` retries).  Must be > 0.
     * The value may be {@code null}.
     */
    private Integer maxAttempts;

    /**
     * The maximum amount of time to wait before retrying a task after it fails. The default is 1
     * hour.
     * <p>
     * * For App Engine queues and tasks, this field is 1 hour by default. * For pull queues and
     * tasks, this field is output only and always 0.
     * The value may be {@code null}.
     */
    private String maxBackoff;

    /**
     * The maximum number of times that the interval between failed task retries will be doubled
     * before the increase becomes constant. The constant is: 2**(max_doublings - 1) *
     * RetryConfig.min_backoff.
     * <p>
     * * For App Engine queues and tasks, this field is 16 by default. * For pull queues and tasks,
     * this field is output only and always 0.
     * The value may be {@code null}.
     */
    private Integer maxDoublings;

    /**
     * The minimum amount of time to wait before retrying a task after it fails.
     * <p>
     * * For App Engine queues and tasks, this field is 0.1 seconds by default. * For pull queues and
     * tasks, this field is output only and always 0.
     * The value may be {@code null}.
     */

    private String minBackoff;

    /**
     * If positive, task_age_limit specifies the time limit for retrying a failed task, measured from
     * when the task was first run. If specified with RetryConfig.max_attempts, the task will be
     * retried until both limits are reached.
     * <p>
     * If zero, then the task age is unlimited. This field is zero by default.
     * The value may be {@code null}.
     */

    private String taskAgeLimit;

    /**
     * If true, then the number of attempts is unlimited.
     * The value may be {@code null}.
     */

    private Boolean unlimitedAttempts;

    /**
     * The maximum number of attempts for a task.
     * <p>
     * Cloud Tasks will attempt the task `max_attempts` times (that is, if the first attempt fails,
     * then there will be `max_attempts - 1` retries).  Must be > 0.
     *
     * @return value or {@code null} for none
     */
    public Integer getMaxAttempts() {
        return maxAttempts;
    }

    /**
     * The maximum number of attempts for a task.
     * <p>
     * Cloud Tasks will attempt the task `max_attempts` times (that is, if the first attempt fails,
     * then there will be `max_attempts - 1` retries).  Must be > 0.
     *
     * @param maxAttempts maxAttempts or {@code null} for none
     */
    public RetryConfig setMaxAttempts(final Integer maxAttempts) {
        this.maxAttempts = maxAttempts;
        return this;
    }

    /**
     * The maximum amount of time to wait before retrying a task after it fails. The default is 1
     * hour.
     * <p>
     * * For App Engine queues and tasks, this field is 1 hour by default. * For pull queues and
     * tasks, this field is output only and always 0.
     *
     * @return value or {@code null} for none
     */
    public String getMaxBackoff() {
        return maxBackoff;
    }

    /**
     * The maximum amount of time to wait before retrying a task after it fails. The default is 1
     * hour.
     * <p>
     * * For App Engine queues and tasks, this field is 1 hour by default. * For pull queues and
     * tasks, this field is output only and always 0.
     *
     * @param maxBackoff maxBackoff or {@code null} for none
     */
    public RetryConfig setMaxBackoff(final String maxBackoff) {
        this.maxBackoff = maxBackoff;
        return this;
    }

    /**
     * The maximum number of times that the interval between failed task retries will be doubled
     * before the increase becomes constant. The constant is: 2**(max_doublings - 1) *
     * RetryConfig.min_backoff.
     * <p>
     * * For App Engine queues and tasks, this field is 16 by default. * For pull queues and tasks,
     * this field is output only and always 0.
     *
     * @return value or {@code null} for none
     */
    public Integer getMaxDoublings() {
        return maxDoublings;
    }

    /**
     * The maximum number of times that the interval between failed task retries will be doubled
     * before the increase becomes constant. The constant is: 2**(max_doublings - 1) *
     * RetryConfig.min_backoff.
     * <p>
     * * For App Engine queues and tasks, this field is 16 by default. * For pull queues and tasks,
     * this field is output only and always 0.
     *
     * @param maxDoublings maxDoublings or {@code null} for none
     */
    public RetryConfig setMaxDoublings(final Integer maxDoublings) {
        this.maxDoublings = maxDoublings;
        return this;
    }

    /**
     * The minimum amount of time to wait before retrying a task after it fails.
     * <p>
     * * For App Engine queues and tasks, this field is 0.1 seconds by default. * For pull queues and
     * tasks, this field is output only and always 0.
     *
     * @return value or {@code null} for none
     */
    public String getMinBackoff() {
        return minBackoff;
    }

    /**
     * The minimum amount of time to wait before retrying a task after it fails.
     * <p>
     * * For App Engine queues and tasks, this field is 0.1 seconds by default. * For pull queues and
     * tasks, this field is output only and always 0.
     *
     * @param minBackoff minBackoff or {@code null} for none
     */
    public RetryConfig setMinBackoff(final String minBackoff) {
        this.minBackoff = minBackoff;
        return this;
    }

    /**
     * If positive, task_age_limit specifies the time limit for retrying a failed task, measured from
     * when the task was first run. If specified with RetryConfig.max_attempts, the task will be
     * retried until both limits are reached.
     * <p>
     * If zero, then the task age is unlimited. This field is zero by default.
     *
     * @return value or {@code null} for none
     */
    public String getTaskAgeLimit() {
        return taskAgeLimit;
    }

    /**
     * If positive, task_age_limit specifies the time limit for retrying a failed task, measured from
     * when the task was first run. If specified with RetryConfig.max_attempts, the task will be
     * retried until both limits are reached.
     * <p>
     * If zero, then the task age is unlimited. This field is zero by default.
     *
     * @param taskAgeLimit taskAgeLimit or {@code null} for none
     */
    public RetryConfig setTaskAgeLimit(final String taskAgeLimit) {
        this.taskAgeLimit = taskAgeLimit;
        return this;
    }

    /**
     * If true, then the number of attempts is unlimited.
     *
     * @return value or {@code null} for none
     */
    public Boolean getUnlimitedAttempts() {
        return unlimitedAttempts;
    }

    /**
     * If true, then the number of attempts is unlimited.
     *
     * @param unlimitedAttempts unlimitedAttempts or {@code null} for none
     */
    public RetryConfig setUnlimitedAttempts(final Boolean unlimitedAttempts) {
        this.unlimitedAttempts = unlimitedAttempts;
        return this;
    }

}
